// MiniCPPSyn.cs                                              HDO, 2006-08-28
// -------------
// Table-driven top-down syntax analyzer (G-code interpreter).
// Generated by Coco-2 (PGT).
//=====================================|========================================

// --- call pragma mehts. and exec. sem. acts. after syntax errors? ---
#define CONTPRAGMAACTS            // !!!must be defined for SG and PGT!!! 
#undef  CONTSEMACTS               // should not be defined 

using System;
using System.Text;

using Lex = MiniCPPLex;
using Sem = MiniCPPSem;

public class MiniCPPSyn {
                   
  public static String MODULENAME = "MiniCPPSyn";

  // --- G-code instructions ---
  public enum Instruction {
    T, TA, TC, TCA, NT, NTA, ANY, ANYA, EPS, EPSA, JMP, RET
  } // Instruction

  private const int ROOTPC     =  731;
  private const int LASTTERM   =   49;
  private const int LASTPRAGMA =   49;


  // --- other constants ---
  private const int MINERRDIST   =   3;
  private const int MAXSTACKLEN  = 100;
  private const int EOFTOK       =   0;
  private const int FIRSTNONTERM = LASTPRAGMA + 1;

  public class NTData {
    public int          startPC;
    public bool         del;
    public Sets.Set256  firstSet;
    public NTData(int startPC, bool del, Sets.Set256 firstSet) {
      this.startPC  = startPC;
      this.del      = del;
      this.firstSet = firstSet;
    } // NTData
  } // NTData
  
  private class GrammarTable {
    public int[]  header = {
      736, 49, 49, 78, 10, 0
    };
    public byte[] code = {
         5,   1,   9,   0,   1,  10,   1,   0,   5,  25,  17,   0,   2,  10,
         1,   0,   8,   1,  15,  11,   0,   7,   4,   6,   1,   2,  48,   2,
         4,   2,   3,   0,  23,  16,  11,   0,  24,   1,   5,  43,   0,  11,
         1,   6,  48,   0,  11,   2,  47,   1,  11,   5,   2,  57,   0,   1,
         1,  22,  76,   0,   1,  37,  65,   0,   2,  48,   2,   5,   2,  57,
         0,   3,  10,  57,   0,   0,  23,  16,  11,   0,  45,   5,   5,  87,
         0,   1,   0,  46,  11,   1,   1, 103,   0,   5,  26, 100,   0,   1,
        11,   8,   2,  11,   4,  27,   2,   4,  26,   3,  11,   1,   1, 115,
         0,  11,   4,  27,   1,  11,   0,  20,   5,   1, 129,   0,   1,  10,
       121,   0,   5,   6, 147,   0,   2,   1,  37, 138,   0,   2,  48,   3,
         4,   3,   4,  10, 121,   0,   5,   8, 155,   0,   5,  10, 121,   0,
         0,  21,  11,   5,  28, 167,   0,   1,   8,   3,  22,  11,   5,  13,
       175,   0,   2,  10, 163,   0,   5,  14, 183,   0,   3,  10, 163,   0,
         5,  15, 191,   0,   4,  10, 163,   0,   5,  16, 199,   0,   5,  10,
       163,   0,   5,  17, 207,   0,   6,  10, 163,   0,   5,  18, 215,   0,
         7,  10, 163,   0,   5,  19, 223,   0,   8,  10, 163,   0,   5,   7,
       231,   0,   9,  10, 163,   0,   0,  23,  10, 163,   0,   4,  20,   1,
        11,   4,  24,   1,   1,  37, 253,   0,   4,  24,   2,  10, 243,   0,
         1,  44,   4,   1,  10, 247,   0,   1,  40,  11,   1,  10, 247,   0,
         8,   4,  11,   1,   5,  19,   1,  11,   1,   6,  24,   1,  11,   3,
        47,  30,   1,   1,  11,   3,  48,  60,   1,   2,   1,  38,  45,   1,
         4,   9,   3,   0,  39,  11,   1,  45,  57,   1,   5,  12,  54,   1,
         4,   0,  46,  11,   8,   5,  11,   1,  16,  75,   1,   4,   6,   5,
         0,  38,   4,   9,   6,   0,  39,  11,   0,  45,   4,   9,   7,   0,
        46,  11,   4,   9,   1,   1,  22,  96,   1,   4,   9,   2,  10,  86,
         1,   8,   2,  11,   0,   8,   0,  45,   4,   9,   1,   0,  46,   4,
         8,   2,   1,  13, 119,   1,   4,   8,   3,  16,   8,   3,  17,  11,
         0,   9,   0,  45,   4,   9,   1,   0,  46,   4,   8,   2,  11,   0,
        10,   0,  23,  11,   0,  11,   0,  28,   2,  48,   1,   0,  23,  11,
         0,  12,   0,  27,   5,   9, 188,   1,   1,   1,  27, 185,   1,   5,
         9, 172,   1,   3,  10, 160,   1,   3,  49, 180,   1,   4,  10, 160,
         1,   0,  17,  10, 160,   1,   0,  23,  11,   3,  49, 196,   1,   2,
        10, 160,   1,   0,  17,  10, 160,   1,   0,  15,   0,  38,   0,  39,
         2,  48,   1,   0,  23,  11,   0,  18,   5,   9, 220,   1,   1,   0,
        23,  11,   4,  21,   1,   1,  29, 236,   1,   4,  21,   2,  10, 226,
         1,   8,   6,  11,   4,  22,   1,   1,  30, 252,   1,   4,  22,   2,
        10, 242,   1,   8,   7,  11,   4,  23,   1,   1,  31,  10,   2,   4,
        23,   2,  11,   1,  32,  17,   2,  10,   6,   2,   1,  43,  24,   2,
        10,   6,   2,   1,  33,  31,   2,  10,   6,   2,   1,  42,  38,   2,
        10,   6,   2,   1,  34,  45,   2,  10,   6,   2,   8,   8,  11,   1,
        35,  75,   2,   4,  10,   1,   1,  35,  65,   2,   4,  10,   2,  10,
        55,   2,   1,  36,  72,   2,  10,  59,   2,   8,   9,  11,   1,  36,
        52,   2,  10,  52,   2,   1,  41,  86,   2,   4,  11,   1,  11,   4,
         6,   1,   1,  37,  97,   2,   2,  48,   2,   5,   3, 106,   2,   3,
        11,   4,   4,   4,   1,  23, 115,   2,  17,  11,   4,   7,   6,  11,
         1,  37, 123,   2,   2,  48,   1,   1,  38, 132,   2,   0,  39,   1,
        22, 155,   2,   4,   6,   2,   1,  37, 143,   2,   2,  48,   3,   1,
        38, 132,   2,   0,  39,  10, 132,   2,   8,   2,  11,   1,  19, 163,
         2,  11,   0,   4,  11,   2,  48,   1,   1,  25, 176,   2,   0,  23,
        11,   1,  26, 183,   2,  10, 173,   2,   1,  38, 200,   2,   4,   9,
         2,   0,  39,   0,  24,   4,   9,   3,  10, 173,   2,   9,  10, 207,
         2,  10, 192,   2,   0,  45,   5,  12, 214,   2,   4,   0,  46,  10,
       173,   2,   4,   0,   1,   0,   0,  11
    };
    public NTData[] nts = {
      new NTData(   1, true , new Sets.Set256(0x0092, 0x0008)),
      new NTData(  21, false, new Sets.Set256(0x0080)),
      new NTData(  36, false, new Sets.Set256(0x0000, 0x0100)),
      new NTData(  52, false, new Sets.Set256(0x0000, 0x01c0)),
      new NTData(  80, false, new Sets.Set256(0x0000, 0x0000, 0x2000)),
      new NTData(  90, false, new Sets.Set256(0x0012, 0x0008)),
      new NTData( 110, false, new Sets.Set256(0x0012, 0x0008)),
      new NTData( 119, false, new Sets.Set256(0x0000, 0x0010)),
      new NTData( 158, false, new Sets.Set256(0x9f00, 0x0094, 0x0000, 0x0001)),
      new NTData( 236, false, new Sets.Set256(0x0060, 0x0001, 0xa218, 0x0001)),
      new NTData( 240, false, new Sets.Set256(0x0060, 0x0001, 0xa200, 0x0001)),
      new NTData( 270, false, new Sets.Set256(0x0060, 0x0001, 0xa000, 0x0001)),
      new NTData( 339, false, new Sets.Set256(0x0060, 0x0001, 0xa218, 0x0001)),
      new NTData( 355, false, new Sets.Set256(0x0100)),
      new NTData( 379, false, new Sets.Set256(0x0200)),
      new NTData( 392, false, new Sets.Set256(0x0400)),
      new NTData( 397, false, new Sets.Set256(0x0800)),
      new NTData( 407, false, new Sets.Set256(0x1000)),
      new NTData( 457, false, new Sets.Set256(0x8000)),
      new NTData( 469, false, new Sets.Set256(0x0000, 0x0004)),
      new NTData( 479, false, new Sets.Set256(0x0060, 0x0001, 0xa218, 0x0001)),
      new NTData( 495, false, new Sets.Set256(0x0060, 0x0001, 0xa218, 0x0001)),
      new NTData( 511, false, new Sets.Set256(0x0060, 0x0001, 0xa218, 0x0001)),
      new NTData( 560, false, new Sets.Set256(0x0060, 0x0001, 0xa218, 0x0001)),
      new NTData( 594, false, new Sets.Set256(0x0060, 0x0001, 0xa200, 0x0001)),
      new NTData( 602, false, new Sets.Set256(0x0012, 0x0008)),
      new NTData( 631, false, new Sets.Set256(0x0000, 0x0000, 0x0020, 0x0001)),
      new NTData( 670, false, new Sets.Set256(0x0010, 0x0008)),
      new NTData( 678, false, new Sets.Set256(0x0000, 0x0000, 0x0000, 0x0001))
    };
    public Sets.Set256[] epsSets = {
      new Sets.Set256(0x0001),
      new Sets.Set256(0x0000, 0x0000, 0x4000),
      new Sets.Set256(0xbf92, 0x00bc, 0x0000, 0x0001),
      new Sets.Set256(0x0000, 0xe8c0, 0x4c9f),
      new Sets.Set256(0x0000, 0xe8c0, 0x5dbf),
      new Sets.Set256(0x0000, 0x08c0, 0x4080),
      new Sets.Set256(0x0000, 0x28c0, 0x4080),
      new Sets.Set256(0x0000, 0x68c0, 0x4080),
      new Sets.Set256(0x0000, 0xe8c0, 0x4c87),
      new Sets.Set256(0x0000, 0x0100)
    };
    public Sets.Set256[] anySets = {
      new Sets.Set256(0x0000)
    };
    public String[] names = {
      "end of file", "void", "scanf", "printf", "int", "false", "true",
      "const", "if", "while", "break", "cin", "cout", "else", "for",
      "delete", "new", "endl", "return", "bool", "{", "}", ",", ";", "=",
      "++", "--", "<<", ">>", "||", "&&", "==", "!=", "<=", ">=", "+", "-",
      "*", "[", "]", "%", "!", ">", "<", "/", "(", ")", "number", "ident",
      "string", "MiniCPP", "ConstDecl", "Init", "VarDef", "FuncHead",
      "FormParList", "Type", "Block", "Stat", "Expr", "Term", "Fact",
      "ActParList", "IfStat", "WhileStat", "BreakStat", "InputStat",
      "OutputStat", "DeleteStat", "ReturnStat", "OrExpr", "AndExpr",
      "RelExpr", "SimpleExpr", "NotFact", "VarDefOrFuncDeclOrDef",
      "FormParListRest", "NonVoidType", "IdentStat"
    };
  } // GrammarTable;

  private static GrammarTable gt;

  private static int   pc;             // G-code counter
  private static int[] stk;            // stack of G-code return adresses
  private static int   sp;             // stack pointer
  private static bool  mustRead;       // next Lex.token to read
  private static int   altRoot;        // root of alternative chain
  private static bool  leaveOrEnter;   // leaveCnt > 0 OR enterCnt > 0
  private static int   leaveCnt;       // nr. of sem. proc. to leave
  private static int   enterCnt;       // nr. of sem. proc. to enter
  private static int   errDist;        // current error distance
  private static int[] stkAtErr;       // saved stack at error position
  private static int[] newSP;          // new stack length
  private static int[] newPC;          // pc after recovery


  public static void MiniCPPSynMethod(Utils.ModuleAction action, out String moduleName) {
  //-----------------------------------|----------------------------------------
    moduleName = MODULENAME;
    switch (action) {
      case Utils.ModuleAction.getModuleName:
        return;
      case Utils.ModuleAction.initModule:
        Errors.InstallStopParsingMethod(StopParsing);
        gt       = new GrammarTable();
        stk      = new int[MAXSTACKLEN];
        stkAtErr = new int[MAXSTACKLEN];
        newSP    = new int[LASTTERM + 1];
        newPC    = new int[LASTTERM + 1];
        break;
      case Utils.ModuleAction.resetModule:
        break;
      case Utils.ModuleAction.cleanupModule:
        gt       = null;
        stk      = null;
        stkAtErr = null;
        newSP    = null;
        newPC    = null;
        break;
    } // switch
  } // MiniCPPSynMethod

  private static void Push(int pc) {
    if (sp < MAXSTACKLEN)
      stk[sp++] = pc;
    else
      Errors.Restriction(MODULENAME, "Push", "parser stack overflow");
  } // Push

  private static int Pop() {
    if (sp > 0)
      return stk[--sp];
    else {
      Errors.CompilerError(MODULENAME, "Pop", "parser stack underflow");
      return 0;
    } // else
  } // Pop

  private static void GetNextToken() {
    for (;;) {
      Lex.GetToken(); // updates Lex.token
      if (Lex.token <= LASTTERM)
        return;
  #if !CONTPRAGMAACTS
      if (NumOfSynErrors() == 0)
  #endif
        Sem.pragmaMethods[Lex.token - LASTTERM - 1]();
    } // for
  } // GetNextToken

  private static int AdrAt(int pc) {
    return (gt.code[pc - 1] |
           (gt.code[pc    ] << 8));
  } // AdrAt

  private static void AdjustPC(ref int pc) {
    if (pc == 0)
      return;
    for (;;)
      switch ((Instruction)gt.code[pc - 1]) {
        case Instruction.T:
        case Instruction.TA:
        case Instruction.TC:
        case Instruction.TCA:
        case Instruction.NT:
        case Instruction.NTA:
        case Instruction.ANY:
        case Instruction.ANYA:
        case Instruction.EPS:
        case Instruction.EPSA:
          return;
        case Instruction.JMP:
          pc = AdrAt(pc + 1);
          break;
        case Instruction.RET:
          pc = 0;
          return;
        default:
          pc++; // syn. or sem. action
          break;
      } // switch
  } // AdjustPC

  private static void GetSymInstr(int pc, 
                        out int opcode, out int sy, out int nextPC, out int altPC) {
    opcode = gt.code[pc - 1];
    nextPC = 0; // dummy init
    altPC  = 0; // dummy init 
    switch ((Instruction)opcode) {
      case Instruction.T:
      case Instruction.TA:
      case Instruction.TC:
      case Instruction.TCA:
      case Instruction.ANYA:
      case Instruction.EPS:
      case Instruction.EPSA:
        sy = gt.code[pc];
        break;
      case Instruction.NT:
      case Instruction.NTA:
        sy = gt.code[pc] + FIRSTNONTERM;
        break;
      default: // ANY, JMP, RET, SEM, SYN 
        sy = 0;
        break;
    } // switch
    switch ((Instruction)opcode) {
      case Instruction.T:
      case Instruction.EPS:
        nextPC = pc + 2;
        altPC = 0;
        break;
      case Instruction.TC:
      case Instruction.NT:
        nextPC = pc + 3;
        altPC = 0;
        break;
      case Instruction.TA:
      case Instruction.ANYA:
      case Instruction.EPSA:
        nextPC = pc + 4;
        altPC = AdrAt(pc + 2);
        break;
      case Instruction.TCA:
      case Instruction.NTA:
        nextPC = pc + 5;
        altPC = AdrAt(pc + 2);
        break;
      case Instruction.ANY:
        nextPC = pc + 1;
        altPC = 0;
        break;
    } // switch
    AdjustPC(ref nextPC);
    AdjustPC(ref altPC);
  } // GetSymInstr

  private static void Fill(int pc, int sp) {
    int opcode, sy, nextPC, altPC, i;
    AdjustPC(ref pc);
    while (pc > 0) {
      GetSymInstr(pc, out opcode, out sy, out nextPC, out altPC);
      switch ((Instruction)opcode) {
        case Instruction.T:
        case Instruction.TA:
        case Instruction.TC:
        case Instruction.TCA:
          newPC[sy] = pc;
          newSP[sy] = sp;
          break;
        case Instruction.NT:
        case Instruction.NTA:
          for (i = 0; i <= LASTTERM; i++)
            if (Sets.member((ushort)i, gt.nts[sy - FIRSTNONTERM].firstSet)) {
              newPC[i] = pc;
              newSP[i] = sp;
            }
          if (gt.nts[sy - FIRSTNONTERM].del)
            Fill(nextPC, sp);
          break;
        case Instruction.EPS:
        case Instruction.EPSA:
          Fill(nextPC, sp);
          break;
      } // switch
      pc = altPC;
    } // while
  } // Fill

  private static void FillSucc(int pc, int sp) {
    int opcode, sy, nextPC, altPC;
    AdjustPC(ref pc);
    while (pc > 0) {
      GetSymInstr(pc, out opcode, out sy, out nextPC, out altPC);
      if (nextPC > 0)
        Fill(nextPC, sp);
      pc = altPC;
    } // while
  } // FillSucc

  private static void Triple(int altRoot) {
    for (int i = 0; i <= LASTTERM; i++) { // clear triple list
      newPC[i] = 0;
      newSP[i] = 0;
    } // for
    for (int i = 1; i <= sp; i++) {       // successors of stacked nt's
      FillSucc(stk[i - 1], i - 1);
      Fill(stk[i - 1], i - 1);
    } // for
    FillSucc(altRoot, sp);                // successors of alt. chain
    Fill(altRoot, sp);                    // current alt. chain
  } // Triple

  private static void HandleSynErr(ref int pc, ref int altRoot) {
    int     opcode, sy, nextPC, altPC, adjPC, nwSP, eq;
    bool    nameInMsg;
    String  name;
    StringBuilder msg = new StringBuilder();
    leaveOrEnter = false;
    if (errDist >= MINERRDIST) { // --- primary error
      nameInMsg = false;
      adjPC = altRoot;
      AdjustPC(ref adjPC);
      while (adjPC > 0) {
        GetSymInstr(adjPC, out opcode, out sy, out nextPC, out altPC);
        if ( (Instruction)opcode >= Instruction.T  && 
             (Instruction)opcode <= Instruction.NTA  ) {
          if ( gt.names[sy].IndexOf(' ') >= 0 || 
               !Char.IsLetter(gt.names[sy][0]) )
            name = "\"" + gt.names[sy] + "\"";
          else
            name = gt.names[sy];
          if (name.IndexOf('{') > -1) // prevent formatting problems in Errors.SynError
            name = name.Replace("{", "{{");
          if (name.IndexOf('}') > -1) // prevent formatting problems in Errors.SynError
            name = name.Replace("}", "}}");
          if (msg.Length + name.Length + 2 > 80) {
            msg.Append(" ...");
            break;
          } // if
          if (!nameInMsg) {
            nameInMsg = true;
            msg.Append("expected: " + name);
          } else {
            msg.Append(", ");
            msg.Append(name);
          } // else
        } // if
        adjPC = altPC;
      } // while
      if (!nameInMsg)
        msg.Append("syntax error");
      Errors.SynError(Lex.tokenLine, Lex.tokenCol, msg.ToString(), "");
      Triple(altRoot);
      while (newPC[Lex.token] == 0) {
        GetNextToken();      // may result in a call to StopParsing
        if (leaveOrEnter)
          return;
      } // while
      nwSP = newSP[Lex.token];
      leaveCnt = sp - nwSP;
      enterCnt = 0;
      Array.Copy(stk, stkAtErr, stk.Length); // save stack
    } else {                 // --- spurios error
      if (errDist == 0) {    // no token used since last error
        GetNextToken();      // may result in a call to StopParsing
        if (leaveOrEnter)
          return;
      } // if
      while (newPC[Lex.token] == 0) {
        GetNextToken();      // may result in a call to StopParsing
        if (leaveOrEnter) 
          return;
      } // while
      nwSP = newSP[Lex.token];
      eq = 2;                // compare stkAtErr and stk
      while (eq <= sp && eq <= nwSP && stkAtErr[eq - 1] == stk[eq - 1])
        eq++;
      eq--;                  // stacks are equal up to index eq
      leaveCnt = sp - eq;
      if (nwSP < eq) {
        leaveCnt = sp - nwSP;
        enterCnt = 0;
      } else if (nwSP > eq)
        enterCnt = nwSP - eq;
      else // nwSP == eq
        enterCnt = 0;
      Array.Copy(stkAtErr, stk, stk.Length); // restore stack
    } // else
    leaveOrEnter = (leaveCnt + enterCnt) > 0;
    sp = nwSP;
    pc = newPC[Lex.token];
    altRoot = pc;
    errDist = 0;
  } // HandleSynErr

  public static int Interpret() {
  //-----------------------------------|----------------------------------------
    int actionNr, opcode, currPC;
    for (;;) {
      opcode = gt.code[pc - 1];
      if ( !leaveOrEnter && mustRead && 
           (Instruction)opcode <= Instruction.EPSA ) {
        GetNextToken();
        mustRead = false;
        errDist++;
        altRoot = pc;
      } // if
      if (leaveOrEnter) {
        if (leaveCnt > 0) {
          leaveCnt--;
          actionNr = 0;
        } else { // enterCnt > 0
          enterCnt--;
          actionNr = gt.code[stkAtErr[sp - enterCnt - 1] - 2];
        } // else
        leaveOrEnter = (leaveCnt + enterCnt) > 0;
        return actionNr;
      } // if
      pc++;
      switch ((Instruction)opcode) {
        case Instruction.T:
          if (Lex.token == gt.code[pc - 1])
            if (Lex.token != EOFTOK) {
              pc++;
              mustRead = true;
            } else {
              return 0;
            } // else
          else
            HandleSynErr(ref pc, ref altRoot);
          break;
        case Instruction.TA:
          if (Lex.token == gt.code[pc - 1]) {
            pc += 3;
            mustRead = true;
          } else
            pc = AdrAt(pc + 1); // try alternative
          break;
        case Instruction.TC:
          if (Lex.token == gt.code[pc - 1]) {
            pc += 2;
            mustRead = true;
            actionNr = gt.code[pc - 2];
            return actionNr;
          } else
            HandleSynErr(ref pc, ref altRoot);
          break;
        case Instruction.TCA:
          if (Lex.token == gt.code[pc - 1]) {
            pc += 4;
            mustRead = true;
            actionNr = gt.code[pc - 2];
            return actionNr;
          } else
            pc = AdrAt(pc + 1); // try alternative
          break;
        case Instruction.NT:
          currPC = gt.code[pc - 1];
          if ( gt.nts[currPC].del || 
               Sets.member((ushort)Lex.token, gt.nts[currPC].firstSet) ) {
            pc++;
            actionNr = gt.code[pc - 1];
            Push(pc + 1);
            pc = gt.nts[currPC].startPC;
            altRoot = pc;
            return actionNr;
          } else
            HandleSynErr(ref pc, ref altRoot);
          break;
        case Instruction.NTA:
          currPC = gt.code[pc - 1];
          if (Sets.member((ushort)Lex.token, gt.nts[currPC].firstSet)) {
            pc += 3;
            actionNr = gt.code[pc - 1];
            Push(pc + 1);
            pc = gt.nts[currPC].startPC;
            altRoot = pc;
            return actionNr;
          } else
            pc = AdrAt(pc + 1);
          break;
        case Instruction.ANY:
          mustRead = true;
          break;
        case Instruction.ANYA:
          currPC = gt.code[pc - 1];
          if (Sets.member((ushort)Lex.token, gt.anySets[currPC - 1])) {
            pc += 3;
            mustRead = true;
          } else
            pc = AdrAt(pc + 1);
          break;
        case Instruction.EPS:
          currPC = gt.code[pc - 1];
          if (Sets.member((ushort)Lex.token, gt.epsSets[currPC - 1]))
            pc++;
          else
            HandleSynErr(ref pc, ref altRoot);
          break;
        case Instruction.EPSA:
          currPC = gt.code[pc - 1];
          if (Sets.member((ushort)Lex.token, gt.epsSets[currPC - 1]))
            pc += 3;
          else
            pc = AdrAt(pc + 1);
          break;
        case Instruction.JMP:
          pc = AdrAt(pc);
          break;
        case Instruction.RET:
          pc = Pop();
          altRoot = pc;
          return 0;
        default:
          if (opcode <= 128) {
  #if !CONTSEMACTS
          if (Errors.NumOfSynErrors() == 0)
  #endif
            return opcode - 12;
          } else // opcode > 128
            return opcode - 128;
          break;
      } // switch
    } // for
  } // Interpret


  public static bool Parse() {
  //-----------------------------------|----------------------------------------
    Lex.InitLex();
    sp           = 0;
    pc           = ROOTPC;
    altRoot      = pc;
    mustRead     = true;
    errDist      = MINERRDIST + 1;
    leaveOrEnter = false;
    leaveCnt     = 0;
    enterCnt     = 0;
    Sem.StartSem();
    return Errors.NumOfSynErrors() == 0;
  } // Parse


  public static void StopParsing() {
  //-----------------------------------|----------------------------------------
    leaveCnt     = sp + 1;
    enterCnt     = 0;
    leaveOrEnter = true;
  } // StopParsing

} // MiniCPPSyn
 
// End of MiniCPPSyn.cs
//=====================================|========================================